### ISSUE TITLE
 Error getting e32 module status.

### ISSUE THREAD

**Issue by Tigre-qui-miaule** [lloydroc/ebyte-sx1276#26]
First of all I want to say that I am a beginner. Many things are new to me, especially GitHub. So I apologize if I don't respect the codes of the community. 
It seems to me that this is where we ask for help when we have a problem.
So, I have a problem that I can't find the source of. I use a raspberry pi 4 with Raspberry PI OS (64-bit) flasher on an sd card with Raspberry Pi Imager.I disabled bluetooth by adding at the bottom of the file "dtoverlay=disable-bt" using the command "sudo nano /boot/config.txt", and running "sudo systemctl disable hciuart".
Then activate serial-port with the command "sudo raspi-config" execute in $. (under Option/ Serial Port interface, serial login shell is disabled and serial interface is disabled).After that I plug in the e32 module as shown, then run the commands to install e32 software. But for some reason when I do "e32 -s"
i get:
"ERROR [ENOENT No such file or directory] timed out

unable to read version
".

Thank you to those who will take the time to answer me.

**Comment by lloydroc** [comment]
Hello Tigre, 

Can you please see this for reference?

https://github.com/lloydroc/ebyte-sx1276/issues/23#issuecomment-1036947484

It seems like you maybe missing the link `/dev/serial0`

Also, can you run with a `e32 -vs` so we can see verbose output?

**Comment by Tigre-qui-miaule** [comment]
Hello Lloydroc,
Thank you for your reply. Indeed my problem is very similar to these: #23 (comment)

but there is no solution to the problem because Yassineelkasmy
finally give up.

The command e32 -vs gives me as output:

option reset is 0
option help is 0
option verbose is 1
option status is 1
option mode is -1
option GPIO M0 Pin is 23
option GPIO M1 Pin is 24
option GPIO AUX Pin is 18
daemon option 0
option TTY Name is /dev/serial0
option socket unix data file desciptor -1
option socket unix control file desciptor -1
opened /dev/serial0
read mode 3
mode 3 unchanged
writing version command
reading version
ERROR [?UNKNOWN? Success] timed out

unable to read version

**Comment by lloydroc** [comment]
Tiger,

It looks like it is very close to working. Can you double check the wiring
again? It appears to me like it is sending the command to the e32 module
but it is getting nothing back.

Lloyd

**Comment by Tigre-qui-miaule** [comment]
Hello Lloyd

I am an idiot. Indeed I had a connection error: I supply my e32 module with 3.3 volts instead of 5! Dude it didn't work. What is surprising is that I communicate with a raspberry pico and it supply his e32 module with 3.3 volts and it works (I managed to send information from the pi 4 to the pico).

Thank you for your help and for taking the time to answer me.
Good continuation you are the best.

**Comment by lloydroc** [comment]
Hi Tiger,

Glad it worked for you! Let me know if you have any other problems.

Lloyd
